# Generated by Django 5.0.3 on 2024-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.DecimalField(decimal_places=1, max_digits=20),
        ),
    ]
