# Generated by Django 5.0.3 on 2024-05-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0003_alter_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product_images/back2.JPG', upload_to='product_images'),
        ),
    ]
